version: "3.8"

services:
  db:
    image: postgres:16
    container_name: business_management_system_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: business_management_system
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: business_management_system_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5433/business_management_system?schema=public
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pgdata:

